[opener]
edit = [
	{ run = '$EDITOR %s', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'nvim %s', desc = "nvim", block = true, for = "windows" },
]

[open]
prepend_rules = [
	{ mime = "text/*", use = "edit" },
	{ url = "*.go", use = "edit" },
	{ url = "*.mod", use = "edit" },
	{ url = "*.sum", use = "edit" },
	{ url = "*.lua", use = "edit" },
	{ url = "*.toml", use = "edit" },
	{ url = "*.yaml", use = "edit" },
	{ url = "*.yml", use = "edit" },
	{ url = "*.json", use = "edit" },
	{ url = "*.md", use = "edit" },
]
